### ISSUE TITLE
Jimp 

### ISSUE THREAD

**Issue by mylastore** [NextFaze/instagram-graph-sdk#1]
First of all, this is awesome.. thanks
Can you be so kind to tell me how to use this package?

**Comment by whimzyLive** [comment]
@mylastore First of all sorry for the delayed response.

So package is available on npm as `instagram-graph-sdk`, so just run `install instagram-graph-sdk`. I will see if I can get some time this week to add some notes on getting started. But once you have it installed, just import modules like you do with any other packages.
